print("welcome")
import time
time.sleep(1)
print (".")
time.sleep(0.5)
print ("..")
time.sleep(0.5)
print ("...")
time.sleep(0.5)
print ("..")
time.sleep(0.5)
print (".")
time.sleep(0.5)
print ("..")
time.sleep(0.5)
print ("...")
time.sleep(0.5)
print ("..")
time.sleep(0.5)
print (".")
time.sleep(1)
print("H̶̢̾è̴̛̦̪͆͒̈́̋͐̚͠͠l̷̮̭̪̇̃ͅl̶̨͉̻͐̈́͂̋́̿̌̄̕ő̷̢͚̠̬͚͍̮͔̼̆̽͐͐͘͜")
time.sleep(1)
print("====================================================================================================HELLO=================")
time.sleep(1)
print("What's your name?")
name=input("type it in here:")
time.sleep(0.5)
print("------cool------")
time.sleep(1)
print(WindowsError)
time.sleep(0.3)
print(WindowsError)
time.sleep(0.3)
print(WindowsError)
time.sleep(0.3)
print(WindowsError)
time.sleep(0.3)
print(WindowsError)
time.sleep(1)
print("no im just kidding")
time.sleep(5)
print("its 20:41 here... its the 2nd of September 2021")
time.sleep(5)
print("i'm watching kitchen nighmares right now...")
time.sleep(5)
print("nvm its hotel hell")
time.sleep(5)
print("anyway probably gonna go to bed rn")
time.sleep(3)
print("frick i didnt finish my german homework, damn oh well its just missing a couple of words")
time.sleep(5)
print("anyways off to bed")
time.sleep(3)
print("gn")
print(name)
time.sleep(3)






